/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  /* tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
   VueJsSidebar: [{type: 'autogenerated', dirName: '.'}],
   LaravelSidebar: [{type: 'autogenerated', dirName: '.'}],*/

  // But you can create a sidebar manually

  LaravelSidebar: [
    {
      type: 'autogenerated',
      dirName: 'laravel',
    }
  ],
  APISidebar: [
    {
      type: "category",
      label: "Tutorials",
      items: ['API/tutorial/intro']
    },
    {
      type: "category",
      label: "Modules",
      items: [{
        type: "autogenerated",
        dirName: "API/modules"
      },
      ]
    },
    {
      type: "category",
      label: "i18n",
      items: ['API/locale/intro']
    }
  ],
};

module.exports = sidebars;
